ALTER TABLE training ADD COLUMN type_gk INTEGER DEFAULT -1 NOT NULL;
ALTER TABLE training ADD COLUMN type_def INTEGER DEFAULT -1 NOT NULL;
ALTER TABLE training ADD COLUMN type_mid INTEGER DEFAULT -1 NOT NULL;
ALTER TABLE training ADD COLUMN type_att INTEGER DEFAULT -1 NOT NULL;
ALTER TABLE player_skills ADD COLUMN training_position INTEGER DEFAULT -1 NOT NULL;
ALTER TABLE player_skills ADD COLUMN training_slot INTEGER DEFAULT -1 NOT NULL;
UPDATE SYSTEM SET VERSION = 26;